ca_blog_homepage:
    path:     /
    defaults: { _controller: CABlogBundle:Blog:index }
 #   defaults: { _controller: CABlogBundle:Default:index }

index:
    path:     /index
    defaults: { _controller: CABlogBundle:Blog:index }
